### ISSUE TITLE
初回起動時のエラー

### ISSUE THREAD

**Issue by ryo2357** [darakuneko/gpk_fwbuilder#2]
electronの問題である気がしますが一応報告させていただきます。

# 発生した現象

exeのインストーラーでインストール後の起動にてTypeError: Cannot read property of undefined (reading 'version')がcreateWindowで発生して起動しない

リポジトリをクローンして、エラーが発生しているコードを編集してnpm startで起動を行うと起動可能

以後、インストールしたgpk_fwbuilderを起動してもエラーは発生しない

# 環境

Windows10HomeEdition

Node:v20.10.0

npm:10.2.3

# 対応

index.jsの下記のように編集

```javascript‘‘
const isRestored = win && state.version === app.getVersion();
// 以下に変更
const isRestored = true;
```

一度electronアプリが起動したら、以後エラーが発生することはなくなった
（元に戻したコードで実行してもインストールしたアプリで起動しても）

**Comment by darakuneko** [comment]
何かしらのタイミングでアプリ終了時に設定ファイルが正しく保存されなかった可能性があります。
正しく設定が読み込まれなくてもエラーが出ないように修正します。

**Comment by darakuneko** [comment]
https://github.com/darakuneko/gpk_fwbuilder/releases/tag/v0.9.2
修正版をリリースしました！
ご報告ありがとうございました！

**Comment by ryo2357** [comment]
ご対応ありがとうございます。
