### ISSUE TITLE
[Error] argument -t/--type: invalid mcu_type value: 'fullsize_ansi'

### ISSUE THREAD

**Issue by is-watering** [darakuneko/gpk_fwbuilder#3]
The following error occurs when performing Convert from KLE Json to QMK/Vial files with GPK FWBuilder v0.10.0.
In v0.9.2 and earlier, I was able to convert without any problem.
After updating to v0.10.0, the error seems to occur when I do an IMEGE REBUILD.

```
Error: Command failed: qmk new-keyboard -kb isw_geode -t fullsize_ansi -l is-watering -u undefined
usage: qmk new-keyboard [-h] [-n REALNAME] [-u NAME] [-t TYPE] [-l LAYOUT]
[-kb KEYBOARD]
qmk new-keyboard: error: argument -t/--type: invalid mcu_type value: 'fullsize_ansi'
```

System Information
* Operating system: Windows 11
* GPK FWBuilder version: 0.10.0

![SS-20240112_235522_069](https://github.com/darakuneko/gpk_fwbuilder/assets/24697900/02a2ed93-385e-45b8-a7ba-719037513e4c)

**Comment by darakuneko** [comment]
a corrected version has been released.
thanks for the report.
https://github.com/darakuneko/gpk_fwbuilder/releases/tag/v0.10.1
