### ISSUE TITLE
[Error] assert.h: No such file or directory

### ISSUE THREAD

**Issue by is-watering** [darakuneko/gpk_fwbuilder#4]
The following error occurs when building firmware with GPK FWBuilder v0.10.2.
The same error occurred in v0.10.1, but v0.9.2 was able to build without problems.

```
Compiling: .build/obj_is_watering_isw_oozy_vial/src/default_keyboard.c In file included from ./lib/pico-sdk/src/common/pico_base/include/pico/types.h:12,
from ./lib/pico-sdk/src/common/pico_base/include/pico.h:24,
from ./lib/pico-sdk/src/rp2_common/hardware_flash/include/hardware/flash.h:10,
from ./platforms/chibios/drivers/wear_leveling/wear_leveling_rp2040_flash_config.h:6,
from :
./lib/pico-sdk/src/common/pico_base/include/pico/assert.h:18:10: fatal error: assert.h: No such file or directory
18 | #include
| ^~~~~~~~~~
compilation terminated.
[ERRORS]
|
|
|
gmake: *** [builddefs/common_rules.mk:373: .build/obj_is_watering_isw_oozy_vial/.build/obj_is_watering_isw_oozy_vial/src/default_keyboard.o] Error 1
```

System Information
* Operating system: Windows 11
* GPK FWBuilder version: 0.10.2

**Comment by darakuneko** [comment]
I don't know what file you are using, but it may be due to a missing or incomplete installation of the compiler toolchain (https://github.com/qmk/qmk_firmware/issues/22291)
Please update the REPOSITORY tab - QMK or VIAL, or IMAGE REBUIL.

**Comment by is-watering** [comment]
Perhaps it was the memory settings in WSL2.
We increased the memory allocation and are now building with v0.10.2 with no problems.
Sorry for the trouble!
